# -*- coding: utf-8 -*-
"""CHANA Preprocessing RGB

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bJbF4TowwXHfR-LbnxxMN6pzOiySeANK
"""

# Cell 1: Environment Setup

!pip install -q scikit-image opencv-python matplotlib pillow imagecodecs

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
from skimage import io, img_as_ubyte
from PIL import Image

print("Environment Ready. Libraries imported.")

# Cell 2: Configuration

from google.colab import drive
drive.mount('/content/drive')

# --- PATHS ---
PROJECT_BASE_PATH = '/content/drive/MyDrive/CHANA_files'
RAW_IMAGES_DIR = os.path.join(PROJECT_BASE_PATH, 'unlabelled_images')

# NEW Output Directory for V8 Data
PREPROCESSED_OUT_DIR = os.path.join(PROJECT_BASE_PATH, 'unlabelled_preprocessed')

# Target Size (Matches your V7.2 Model Input)
TARGET_SIZE = (512, 512)

print(f"📂 INPUT:  {RAW_IMAGES_DIR}")
print(f"📂 OUTPUT: {PREPROCESSED_OUT_DIR}")

os.makedirs(PREPROCESSED_OUT_DIR, exist_ok=True)

# Cell 3: V9 "Nuclear Pop" Preprocessing (Top-Hat + CLAHE)

def surgical_rgb_enhance(image_path, target_size=(512, 512)):
    """
    V9 Pipeline:
    1. Robust Load & Resize.
    2. Convert to LAB.
    3. L-Channel CLAHE (Global Contrast).
    4. L-Channel White Top-Hat (Highlight 'Lighter' Nuclei).
    5. Fusion: Add Top-Hat signal to enhanced L-Channel.
    6. Merge & Return RGB.
    """
    # --- 1. Robust Loading ---
    img = None
    try:
        img = io.imread(image_path)
        if img.ndim == 2: img = cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)
        elif img.shape[2] == 4: img = img[:, :, :3]
    except:
        try:
            pil_img = Image.open(image_path).convert('RGB')
            img = np.array(pil_img)
        except: return None

    if img is None: return None
    img = cv2.resize(img, target_size, interpolation=cv2.INTER_AREA)

    # --- 2. Color Space Conversion ---
    # We work in LAB to decouple "Lightness" (Structure) from "Color" (Chemistry)
    lab = cv2.cvtColor(img, cv2.COLOR_RGB2LAB)
    l, a, b = cv2.split(lab)

    # --- 3. Step A: Global Contrast (CLAHE) ---
    # This sets the stage by fixing lighting drift
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
    l_clahe = clahe.apply(l)

    # --- 4. Step B: "Hole" Extraction (White Top-Hat) ---
    # We define a "kernel" size roughly the size of a nucleus (e.g., 15x15 pixels)
    # This filter finds "bright things approx 15px wide"
    kernel_size = (15, 15)
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, kernel_size)

    # Apply White Top-Hat: Extracts BRIGHT objects on DARK background
    nuclei_map = cv2.morphologyEx(l_clahe, cv2.MORPH_TOPHAT, kernel)

    # --- 5. Step C: Fusion (Accentuate) ---
    # We ADD the nuclei map back to the image.
    # This makes the "lighter" nuclei significantly brighter.
    # alpha=1.0 (Base), beta=1.5 (Boost factor for nuclei)
    l_final = cv2.addWeighted(l_clahe, 1.0, nuclei_map, 0.8, 0)

    # Merge back
    lab_merged = cv2.merge((l_final, a, b))
    final_img = cv2.cvtColor(lab_merged, cv2.COLOR_LAB2RGB)

    return final_img

print("✅ V9 Pipeline Defined: Includes Top-Hat Morphological Boosting.")

# Cell 4: Batch Processing

valid_exts = ('.tif', '.tiff', '.png', '.jpg')
files = [f for f in os.listdir(RAW_IMAGES_DIR) if f.lower().endswith(valid_exts)]

print(f"🚀 Starting Batch Process for {len(files)} images...")

success_count = 0
for fname in files:
    in_path = os.path.join(RAW_IMAGES_DIR, fname)
    out_name = os.path.splitext(fname)[0] + '.png' # Save as PNG (Lossless)
    out_path = os.path.join(PREPROCESSED_OUT_DIR, out_name)

    # Process
    processed_img = surgical_rgb_enhance(in_path, TARGET_SIZE)

    if processed_img is not None:
        # Save as BGR (OpenCV standard)
        cv2.imwrite(out_path, cv2.cvtColor(processed_img, cv2.COLOR_RGB2BGR))
        success_count += 1
        if success_count % 100 == 0: print(f"   ... Processed {success_count} images")

print(f"\n✅ DONE. {success_count} images saved to: {PREPROCESSED_OUT_DIR}")

# Cell 5: Visual Verification

def visualize_comparison():
    raw_files = sorted(os.listdir(RAW_IMAGES_DIR))[:3]

    plt.figure(figsize=(12, 12))

    for i, fname in enumerate(raw_files):
        # Load Raw
        raw_path = os.path.join(RAW_IMAGES_DIR, fname)
        raw = io.imread(raw_path)
        if raw.ndim == 2: raw = cv2.cvtColor(raw, cv2.COLOR_GRAY2RGB)
        elif raw.shape[2] == 4: raw = raw[:,:,:3]
        raw = cv2.resize(raw, TARGET_SIZE)

        # Load Processed (V8)
        out_name = os.path.splitext(fname)[0] + '.png'
        proc_path = os.path.join(PREPROCESSED_OUT_DIR, out_name)
        if not os.path.exists(proc_path): continue

        proc = cv2.imread(proc_path)
        proc = cv2.cvtColor(proc, cv2.COLOR_BGR2RGB) # Fix CV2 loading

        # Plot
        plt.subplot(3, 2, i*2 + 1)
        plt.imshow(raw)
        plt.title(f"Raw: {fname}")
        plt.axis('off')

        plt.subplot(3, 2, i*2 + 2)
        plt.imshow(proc)
        plt.title("Surgical RGB (L-CLAHE)")
        plt.axis('off')

    plt.tight_layout()
    plt.show()

visualize_comparison()

# ==============================================================================
# STANDALONE QUANTITATIVE DIAGNOSIS: SEPARABILITY TEST
# ==============================================================================
import os
import cv2
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from skimage import io
from scipy.stats import wasserstein_distance

def analyze_separability(raw_dir, mask_dir, prep_dir, target_size=(512, 512)):
    """
    Quantifies how much the preprocessing improved the statistical
    separation between target cells (Osteoclasts) and background debris.
    """
    print("🔬 RUNNING SEPARABILITY DIAGNOSIS (Target vs. Distractors)...")

    # Tracking data
    raw_distances = []
    prep_distances = []

    # Filter for image files
    files = sorted([f for f in os.listdir(raw_dir) if f.lower().endswith(('.tif', '.png', '.jpg'))])

    # Process a representative sample (50 images) for statistical significance
    sample_files = files[:50]

    for fname in sample_files:
        base = os.path.splitext(fname)[0]

        # 1. Path Construction
        raw_path = os.path.join(raw_dir, fname)
        # Check for multiple possible mask extensions
        mask_path = None
        for ext in ['_mask.png', '_mask.tif', '.png', '.tif']:
            p = os.path.join(mask_dir, base + ext)
            if os.path.exists(p):
                mask_path = p
                break

        prep_path = os.path.join(prep_dir, base + '.png')

        if not mask_path or not os.path.exists(prep_path):
            continue

        # 2. Load and Prepare Data
        try:
            # Raw Data: Convert to LAB and extract Luminance (L)
            raw = io.imread(raw_path)
            if raw.ndim == 2: raw = cv2.cvtColor(raw, cv2.COLOR_GRAY2RGB)
            elif raw.shape[2] == 4: raw = raw[:,:,:3]
            raw = cv2.resize(raw, target_size)
            raw_l = cv2.cvtColor(raw, cv2.COLOR_RGB2LAB)[:,:,0]

            # Preprocessed Data: Extract Luminance
            prep_img = cv2.imread(prep_path)
            prep_l = cv2.cvtColor(prep_img, cv2.COLOR_BGR2LAB)[:,:,0]

            # Ground Truth Mask
            mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)
            mask = cv2.resize(mask, target_size, interpolation=cv2.INTER_NEAREST)
            mask_bin = (mask > 0).astype(np.uint8)

            # 3. Create "Distractor" Mask
            # Use Otsu's thresholding to find all non-background stained tissue
            _, all_tissue = cv2.threshold(raw_l, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)

            # Distractors = (Everything Stained) - (True Expert-Labeled Osteoclasts)
            # This isolates the debris and stem cells the AI might confuse with osteoclasts
            distractors = cv2.bitwise_and(all_tissue, all_tissue, mask=(1-mask_bin).astype(np.uint8))

            # 4. Extract Pixel Distributions
            raw_target_pix = raw_l[mask_bin == 1]
            raw_distractor_pix = raw_l[distractors > 0]

            prep_target_pix = prep_l[mask_bin == 1]
            prep_distractor_pix = prep_l[distractors > 0]

            # Ensure we have enough pixels to compare
            if len(raw_target_pix) < 10 or len(raw_distractor_pix) < 10:
                continue

            # 5. Measure Statistical Distance (Wasserstein)
            # Higher distance = cleaner signal for the U-Net to learn
            d_raw = wasserstein_distance(raw_target_pix, raw_distractor_pix)
            d_prep = wasserstein_distance(prep_target_pix, prep_distractor_pix)

            raw_distances.append(d_raw)
            prep_distances.append(d_prep)

        except Exception as e:
            continue

    # --- PLOT & REPORT RESULTS ---
    if not raw_distances:
        print("❌ ERROR: No matching files found. Check your directory paths.")
        return

    plt.figure(figsize=(10, 6))
    plot_df = pd.DataFrame({
        'Distance': raw_distances + prep_distances,
        'Condition': ['Raw Input'] * len(raw_distances) + ['CHANA Preprocessed'] * len(prep_distances)
    })

    sns.boxplot(x='Condition', y='Distance', data=plot_df, palette="husl")
    plt.title("Preprocessing Efficacy: Osteoclasts vs. Biological Noise", fontsize=14, fontweight='bold')
    plt.ylabel("Wasserstein Distance (Separability Score)")
    plt.grid(True, linestyle='--', alpha=0.6)
    plt.show()

    avg_raw = np.mean(raw_distances)
    avg_prep = np.mean(prep_distances)
    improvement = ((avg_prep - avg_raw) / avg_raw) * 100

    print(f"\n" + "="*50)
    print(f"📊 DATA SEPARABILITY SUMMARY")
    print(f"="*50)
    print(f"Baseline Separability (Raw):      {avg_raw:.2f}")
    print(f"Enhanced Separability (Prep):     {avg_prep:.2f}")
    print(f"Mathematical Signal Boost:        {improvement:.1f}%")
    print("-" * 50)

    if avg_prep > avg_raw:
        print(f"✅ SUCCESS: Preprocessing enhanced the biological signal by {improvement:.1f}%.")
    else:
        print("⚠️ WARNING: Preprocessing reduced separability. Check Contrast/CLAHE settings.")

# --- CONFIGURE PATHS AND RUN ---
# Update these to match your specific Google Drive or local folders
BASE_PATH = '/content/drive/MyDrive/CHANA_files'
RAW_DIR = os.path.join(BASE_PATH, 'original_images')
MASK_DIR = os.path.join(BASE_PATH, 'mask_images_512')
PREP_DIR = os.path.join(BASE_PATH, 'preprocessed_rgb')

analyze_separability(RAW_DIR, MASK_DIR, PREP_DIR)

from google.colab import drive
drive.mount('/content/drive')

# Cell 7: Visualizing the Logic (Raw -> Otsu -> Distractors)

def visualize_separability_logic(index=0):
    files = sorted([f for f in os.listdir(RAW_IMAGES_DIR) if f.lower().endswith(('.tif', '.png'))])
    if len(files) == 0: return
    fname = files[index]
    base = os.path.splitext(fname)[0]

    # 1. Load Everything
    raw_path = os.path.join(RAW_IMAGES_DIR, fname)
    prep_path = os.path.join(PREPROCESSED_OUT_DIR, base + '.png')

    # Find Mask
    mask_name = base + '_mask.png'
    if not os.path.exists(os.path.join(PROJECT_BASE_PATH, 'mask_images_512', mask_name)):
        mask_name = base + '_mask.tif'
    mask_path = os.path.join(PROJECT_BASE_PATH, 'mask_images_512', mask_name)

    # Read Images
    raw = io.imread(raw_path)
    if raw.ndim == 2: raw = cv2.cvtColor(raw, cv2.COLOR_GRAY2RGB)
    elif raw.shape[2] == 4: raw = raw[:,:,:3]
    raw = cv2.resize(raw, TARGET_SIZE)
    raw_l = cv2.cvtColor(raw, cv2.COLOR_RGB2LAB)[:,:,0] # L-Channel

    prep = cv2.imread(prep_path)
    prep = cv2.cvtColor(prep, cv2.COLOR_BGR2RGB) # RGB for display

    mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)
    if mask is None: mask = io.imread(mask_path)
    mask = cv2.resize(mask, TARGET_SIZE, interpolation=cv2.INTER_NEAREST)
    mask_bin = (mask > 0).astype(np.uint8)

    # 2. Recreate the Logic Steps
    # Step A: Otsu Threshold on Raw L-Channel (Find ALL foreground)
    # Note: We use BINARY_INV because in L-channel, tissue is darker (lower value) than white background
    otsu_val, all_tissue = cv2.threshold(raw_l, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)

    # Step B: Identify Distractors (Foreground MINUS Osteoclasts)
    # "True Target" is mask_bin. "All Tissue" is Otsu.
    # Distractors = (All Tissue) - (True Targets)
    distractors = cv2.bitwise_and(all_tissue, all_tissue, mask=(1-mask_bin).astype(np.uint8))

    # 3. Plot
    plt.figure(figsize=(20, 10))

    # Row 1: The Inputs
    plt.subplot(2, 3, 1)
    plt.imshow(raw)
    plt.title(f"1. Raw Image (RGB)\n{fname}")
    plt.axis('off')

    plt.subplot(2, 3, 2)
    plt.imshow(raw_l, cmap='gray')
    plt.title("2. L-Channel (Luminance)\nInput for Otsu")
    plt.axis('off')

    plt.subplot(2, 3, 3)
    plt.imshow(mask_bin, cmap='gray')
    plt.title("3. Ground Truth Mask\n(The Osteoclasts)")
    plt.axis('off')

    # Row 2: The Logic
    plt.subplot(2, 3, 4)
    plt.imshow(all_tissue, cmap='gray')
    plt.title(f"4. Otsu Threshold (All Tissue)\nSplits Tissue vs. Empty Glass")
    plt.axis('off')

    plt.subplot(2, 3, 5)
    # Create a red overlay for distractors on the raw image
    overlay = raw.copy()
    overlay[distractors > 0] = (255, 0, 0) # Paint distractors RED
    plt.imshow(overlay)
    plt.title("5. 'Hard Distractors' (Red)\n(Otsu MINUS Ground Truth)")
    plt.axis('off')

    plt.subplot(2, 3, 6)
    plt.imshow(prep)
    plt.title(f"6. V8 Enhanced Output\n")
    plt.axis('off')

    plt.tight_layout()
    plt.show()

# Visualize the first few images to check consistency
for i in [0, 5, 10]:
    try:
        visualize_separability_logic(i)
    except: pass