# -*- coding: utf-8 -*-
"""ImageTiler

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lmBmT680ZIIaafRnP4R9_T9_D1CwEoE8
"""

import os
import numpy as np
from PIL import Image
from google.colab import drive # For mounting Google Drive

# --- 1. Mount Google Drive ---
# This connects your Google Drive to the Colab environment.
print("Mounting Google Drive...")
drive.mount('/content/drive')
print("Google Drive mounted successfully!")

# Define your base Google Drive path.
# This assumes your 'Tile_Images' folder will be directly under 'My Drive'.
# If you want it in a subfolder (e.g., 'My Drive/My Projects'), adjust this path.
# IMPORTANT: Update this path to your specific Google Drive directory.
google_drive_base_path = '/content/drive/MyDrive/CHANA_files'

# --- 2. Get the image files from a directory ---
# We'll assume your input images are on Google Drive in a specified directory.
# Please update 'input_images_dir' to the actual path of the directory
# containing your input image files on Google Drive.
# IMPORTANT: Update this path to your specific Google Drive directory.
input_images_dir = os.path.join(google_drive_base_path, 'tiling images') # Assuming images are directly in Ita3

print(f"Attempting to find images in directory: {input_images_dir}")

# Use os.listdir() with the input_images_dir to get a list of all files and directories within that directory.
all_files_in_dir = []
try:
    all_files_in_dir = os.listdir(input_images_dir)
except FileNotFoundError:
    print(f"Error: Directory '{input_images_dir}' not found.")
    print("Please ensure the path is correct and the directory exists in your Google Drive.")
except Exception as e:
    print(f"An error occurred while accessing the directory: {e}")


# Filter the list obtained in the previous step to include only image files (e.g., files ending with '.tif', '.tiff', '.png', '.jpg', etc., depending on the expected image formats).
# You can use a list comprehension and str.lower().endswith() for this filtering.
image_extensions = ('.tif', '.tiff', '.png', '.jpg', '.jpeg')
image_files = [f for f in all_files_in_dir if os.path.isfile(os.path.join(input_images_dir, f)) and f.lower().endswith(image_extensions)]

# Store the list of image filenames in a variable, for example image_files.
# The variable 'image_files' now holds the list of image filenames.

print(f"Found {len(image_files)} image files in directory: {input_images_dir}")
if len(image_files) == 0:
    print("No image files found in the directory. Please check the directory path and file extensions.")
else:
    print("Image files found:")
    for img_file in image_files:
        print(img_file)

    # --- 3. Define output directory on Google Drive ---
    # This will create a 'Tile_Images' folder directly under the base path
    # and then a 'maskImage2' subfolder within it, just like your original macro.
    output_drive_base_dir = os.path.join(google_drive_base_path, 'unlabelled_images')


    # Create the base output directory if it doesn't exist. exist_ok=True prevents an error
    # if the directory already exists.
    os.makedirs(output_drive_base_dir, exist_ok=True)
    print(f"Base output directory on Google Drive: {output_drive_base_dir}")


    # --- 4. Process each image file ---
    for image_filename in image_files:
        image_path_on_drive = os.path.join(input_images_dir, image_filename)
        print(f"\nProcessing image: {image_filename}")

        try:
            img_pil = Image.open(image_path_on_drive)
        except FileNotFoundError:
            print(f"Error: Image file '{image_path_on_drive}' not found. Skipping.")
            continue # Skip to the next image if the file is not found
        except Exception as e:
            print(f"An error occurred while opening the image '{image_filename}': {e}. Skipping.")
            continue # Skip to the next image on error

        # --- Crop the center 3/4 of the image ---
        width, height = img_pil.size
        new_width = width * 1
        new_height = height * 1
        left = (width - new_width)/2
        top = (height - new_height)/2
        right = (width + new_width)/2
        bottom = (height + new_height)/2
        img_pil = img_pil.crop((left, top, right, bottom))


        # Get basic image information
        # Get filename without extension as title
        title = os.path.splitext(os.path.basename(image_path_on_drive))[0]

        # Get dimensions (assuming img_pil is a multi-frame TIFF if sizeZ > 1)
        width, height = img_pil.size
        # Number of slices/frames; uses .n_frames for multi-frame TIFFs, defaults to 1
        sizeZ = img_pil.n_frames if hasattr(img_pil, 'n_frames') else 1

        print(f"Image Title: {title}")
        print(f"Image Dimensions: Width={width}, Height={height}, Slices (Z)={sizeZ}")

        # --- Define output directory for the current image ---
        # This creates a subfolder within 'Tile_Images' for each image being processed
        sliced_dir = output_drive_base_dir

        # Create the image-specific output directory if it doesn't exist.
        os.makedirs(sliced_dir, exist_ok=True)
        print(f"Output directory for {image_filename}: {sliced_dir}")


        # --- 5. Define tiling parameters ---
        # These are derived from the current image's dimensions.
        # For a 2x2 grid, each tile will be half the width and half the height.
        # The depth (sizeZ) remains the same for each tile.
        tile_width = 512
        tile_height = 512
        tile_depth = sizeZ # Equivalent to sizeZ from the macro

        print(f"Tile Dimensions: Width={tile_width}, Height={tile_height}, Depth={tile_depth}")

        # Initialize tile counter for the current image
        i = 1

        # --- 6. Tile and Save to Google Drive ---
        # The loops below create a 3x3 grid of tiles.
        # If you intend a 2x2 grid, change range(3) to range(2) for both loops.
        for y_idx in range(15): # Y-loop for vertical sections (0, 1, 2)
            offset_y = y_idx* tile_height
            for x_idx in range(14): # X-loop for horizontal sections (0, 1, 2)
                offset_x = x_idx * tile_width

                # List to hold all slices for the current tile
                current_tile_slices = []

                # Iterate through all slices (Z-dimension) for the current tile
                for z_slice_idx in range(sizeZ):
                    # Move to the specific slice in the multi-frame TIFF
                    img_pil.seek(z_slice_idx)
                    # Get a copy of the current slice to avoid modifying the original
                    current_slice = img_pil.copy()

                    # Crop the current slice based on the calculated offsets and tile dimensions
                    cropped_slice = current_slice.crop((offset_x, offset_y, offset_x + tile_width, offset_y + tile_height))
                    current_tile_slices.append(cropped_slice)

                # Construct the new filename for the tile
                new_name = f"{title}_Tile_{i}.tif"
                # Construct the full save path on Google Drive
                save_path = os.path.join(sliced_dir, new_name)

                # Save the tiled image (potentially multi-slice TIFF)
                if len(current_tile_slices) > 1:
                    # If there's more than one slice, save as a multi-page TIFF.
                    # The first slice is saved, and subsequent slices are appended.
                    current_tile_slices[0].save(save_path, save_all=True, append_images=current_tile_slices[1:])
                else:
                    # If there's only one slice, save as a single-page TIFF.
                    current_tile_slices[0].save(save_path)

                print(f"Saved: {save_path}")
                i += 1 # Increment tile counter

    print("\nAll image tiling complete and saved to Google Drive!")

from google.colab import drive
drive.mount('/content/drive')